---
- name: Install telegraf
  yum:
    name: telegraf
    state: present
- name: Install Config file
  template:
    src: telegraf.conf.j2
    dest: /etc/telegraf/telegraf.conf
    owner: root
    group: root
    mode: "0644"
  vars:
    gpfs_snmp_host: "playbook_none"
  notfiy: "restart telegraf"
  