---
- name: Local Centos Base OS repo
  yum_repository:
    name: local-centos-base
    description: Local centos repo
    baseurl: "{{local_repo_base_url}}os"
    gpgcheck: no
    proxy: "_none_"
    enabled: yes
    file: local
  when: use_local_centos|bool
- name: Local Centos Updates repo
  yum_repository:
    name: local-centos-updates
    description: Local centos updates
    baseurl: "{{local_repo_base_url}}updates"
    gpgcheck: no
    proxy: "_none_"
    enabled: yes
    file: local
  when: use_local_centos|bool
- name: Local Centos Extras repo
  yum_repository:
    name: local-centos-extras
    description: Local centos extras
    baseurl: "{{local_repo_base_url}}extras"
    gpgcheck: no
    proxy: "_none_"
    enabled: yes
    file: local
  when: use_local_centos|bool
- name: Centos SCL Repo
  yum_repository:
    name: local-centos-scl
    description: Local centos SCL
    baseurl: "{{local_repo_base_url}}sclo"
    gpgcheck: no
    proxy: "_none_"
    enabled: yes
    file: local
  when: use_local_centos|bool
- name: Local Centos epel repo
  yum_repository:
    name: epel
    description: Local centos epel updates
    baseurl: "{{local_repo_base_url}}epel"
    gpgcheck: no
    proxy: "_none_"
    enabled: no
    file: local
  when: use_local_centos|bool
- name: PGDG PostgreSQL repo
  yum_repository:
    name: pgdg11
    description: PGDG PostgreSQL 11 repo
    baseurl: "{{local_repo_base_url}}pgdg11"
    gpgcheck: no
    proxy: "_none_"
    enabled: no
    file: local
- name: Local RPMS
  yum_repository:
    name: local
    description: Locally built packages
    baseurl: "{{local_repo_base_url}}local"
    gpgcheck: no
    proxy: "_none_"
    enabled: yes
    file: local
- name: Remove epel-release package
  yum:
    name: epel-release
    state: absent
  when: use_local_centos|bool
- name: disable default repos
  command: "yum-config-manager --disable base,extras,updates,epel"
  when: use_local_centos|bool
- yum_repository:
    baseurl: "{{gpfs_repo_base_url}}gpfs_rpms"
    description: "GPFS Base rpms"
    name: gpfs_base
    proxy: "_none_"
    gpgcheck: no
    file: gpfs
    enabled: yes
  name: gpfs base repo
- yum_repository:
    baseurl: "{{gpfs_repo_base_url}}gplbin"
    description: "GPFS Kernel Module rpms"
    name: gpfs_gplbin
    proxy: "_none_"
    gpgcheck: no
    file: gpfs
    enabled: yes
  name: gpfs gplbin repo
- yum_repository:
    baseurl: "{{gpfs_repo_base_url}}zimon_rpms"
    description: "GPFS monitoring RPMS"
    name: gpfs_zimon
    proxy: "_none_"
    gpgcheck: no
    file: gpfs
    enabled: yes
- yum_repository:
    baseurl: "{{gpfs_repo_base_url}}ganesha_rpms"
    description: "GPFS NFS RPMS"
    name: gpfs_ganesha
    proxy: "_none_"
    gpgcheck: no
    file: gpfs
    enabled: no
- yum_repository:
    baseurl: "{{gpfs_repo_base_url}}object_rpms"
    description: "GPFS Object RPMS"
    name: gpfs_object
    proxy: "_none_"
    gpgcheck: no
    file: gpfs
    enabled: no
- yum_repository:
    baseurl: "{{gpfs_repo_base_url}}smb_rpms"
    description: "GPFS SMB RPMS"
    name: gpfs_smb
    proxy: "_none_"
    gpgcheck: no
    file: gpfs
    enabled: no
