---
- name: install ipa-client packages
  yum:
    name:
      - ipa-client
    state: present
  # --automount-location=cluster
- command: "ipa-client-install --domain={{ipa_domain}} -p admin -N -w {{ipa_default_password}} -U  --force-join"
  args:
    creates: /etc/ipa/default.conf
    chdir: /root
- name: krb5 dns config
  ini_file:
    path: /etc/krb5.conf.d/dns.conf
    section: libdefaults
    option: dns_canonicalize_hostname
    value: "true"
    owner: root
    group: root
    mode: "0644"
