---
- name: install GPFS path profile
  template: src=gpfs.sh.j2 dest=/etc/profile.d/gpfs.sh owner=root group=root mode="0644"
- name: install gpfs packages
  yum:
    name: "{{ gpfs_packages }}"
    state: "present"
    enablerepo: "{{ gpfs_repos }}"
