---
- yum_repository:
    baseurl: "{{gpfs_repo_base}}gpfs_rpms"
    description: "GPFS Base rpms"
    name: gpfs_base
    proxy: "_none_"
    gpgcheck: no
    file: gpfs
  name: gpfs base repo
- yum_repository:
    baseurl: "{{gpfs_repo_base}}gplbin"
    description: "GPFS Kernel Module rpms"
    name: gpfs_gplbin
    proxy: "_none_"
    gpgcheck: no
    file: gpfs
  name: gpfs gplbin repo
- yum_repository:
    baseurl: "{{gpfs_repo_base}}zimon_rpms"
    description: "GPFS monitoring RPMS"
    name: gpfs_zimon
    proxy: "_none_"
    gpgcheck: no
    file: gpfs
- yum_repository:
    baseurl: "{{gpfs_repo_base}}ganesha_rpms"
    description: "GPFS NFS RPMS"
    name: gpfs_ganesha
    proxy: "_none_"
    gpgcheck: no
    file: gpfs
- yum_repository:
    baseurl: "{{gpfs_repo_base}}object_rpms"
    description: "GPFS Object RPMS"
    name: gpfs_object
    proxy: "_none_"
    gpgcheck: no
    file: gpfs
- yum_repository:
    baseurl: "{{gpfs_repo_base}}smb_rpms"
    description: "GPFS SMB RPMS"
    name: gpfs_smb
    proxy: "_none_"
    gpgcheck: no
    file: gpfs
- name: install GPFS path profile
  template: src=gpfs.sh.j2 dest=/etc/profile.d/gpfs.sh owner=root group=root mode="0644"
- name: install gpfs packages
  yum: 
    name: "{{ gpfs_packages }}"
    state: "present"
- name: install gpfs kernel modules rpm
  yum:
    name: "gpfs.gplbin-{{ansible_kernel}}"
    state: "present"
# - name: Build kernel modules
#   command: bash -c "LINUX_DISTRIBUTION=REDHAT_AS_LINUX make Autoconfig World InstallImages"
#   args:
#     chdir: /usr/lpp/mmfs/src
#     creates: /lib/modules/{{ansible_kernel}}/extra/*.ko
