---
- block:
    - name: Install chronyd
      yum:
        name: chrony
        state: present
    - name: Install chronyd configuration
      template:
        src: chrony.conf.j2
        dest: /etc/chrony.conf
        mode: "0640"
        owner: root
        group: root
      notify: restart chronyd
  when: is_aws_environment|bool
