---
- name: create node_file
  template:
    src: node_file.j2
    dest: /root/node_file
- name: create node_license files
  template:
    src: node_license.j2
    dest: "/root/node_license.{{license_type}}"
  loop:
    - server
    - client
    # - fpo
  loop_control:
    loop_var: license_type

- name: cluster creation script
  template:
    src: create_cluster.j2
    dest: /root/create_cluster.sh
    mode: '0755'
