---
- template:
    src: node_file.j2
    dest: /root/node_file
- template:
    src: node_license.j2
    dest: "/root/node_license.{{license_type}}"
  loop:
    - server
    - client
    # - fpo
  loop_control:
    loop_var: license_type
