---
- name: Install grafana
  yum:
    name: grafana
    state: present
  notify: grafana
- name: Install http proxy def
  copy:
    src: httpd-grafana.conf
    dest: /etc/httpd/conf.d/grafana.conf
    owner: root
    group: root
    mode: '0644'
  notify: reload web
- name: Install grafana config
  copy:
    src: grafana.ini
    dest: /etc/grafana/grafana.ini
    owner: root
    group: grafana
    mode: '0640'
  notify: grafana
- name: install influxdb datasource
  copy:
    src: local_influxdb.yaml
    dest: /etc/grafana/provisioning/datasources/
    owner: root
    group: grafana
    mode: '0640'
  notify: grafana
- name: install system monitoring dashboards
  copy:
    src: "{{item}}"
    dest: /etc/grafana/provisioning/dashboards/
    owner: root
    group: grafana
    mode: '0640'
    directory_mode: '0755'
  loop:
    - system_dashboards
    - system_dashboards.yaml
  notify: grafana
- name: install gpfs-opentsdb data source
  template:
    src: gpfs_opentsdb.yaml
    dest: /etc/grafana/provisioning/datasources/
    owner: root
    group: grafana
    mode: '0640'
  notify: grafana