---
- name: Distro-specific vars include
  include_vars:
    file: "rhel{{ansible_distribution_major_version}}.yml"
- name: Distro-specific repo include
  include_tasks: "rhel{{ansible_distribution_major_version}}.yml"

# Local RPM repo
- block:
    - name: Locally built RPMS - distro specific
      yum_repository:
        name: "local-rpms"
        description: "Locally built RPMS"
        baseurl: "{{repo_base_url}}/local-rpm/$releasever/$basearch"
        gpgcheck: no
        enabled: no
        file: local
        cost: "10"
  when: local_repo|bool

# JC21 misc repo
- block:
    - name: JC21 misc repo
      yum_repository:
        name: "jc21"
        description: "JC21 misc repo"
        baseurl: "{{repo_base_url}}/jc21/centos/base/el/all/"
        gpgcheck: no
        enabled: no
        file: jc21
        cost: "10"
  when: local_repo|bool

# Local GPFS RPMS
- block:
    - name: Local GPFS RPMS
      yum_repository:
        name: "local-{{item}}"
        description: "Local centos repo {{item}}"
        baseurl: "{{repo_base_url}}/gpfs/{{item}}"
        gpgcheck: no
        enabled: no
        file: local-gpfs
        cost: "10"
      loop: "{{gpfs_repos}}"
  when: local_repo|bool
