---
# Centos Repos
- block:
  - name: Local Centos Base OS repo
    yum_repository:
      name: "local-centos-{{item}}"
      description: "Local centos repo {{item}}"
      baseurl: "{{repo_base_url}}/centos/$releasever/{{item}}/$basearch"
      gpgcheck: no
      proxy: "_none_"
      enabled: yes
      file: local-centos
      cost: "10"
    loop: "{{centos_repos}}"
  - name: Disable default Centos repos
    command: "yum-config-manager --disable {{item}}"
    loop:
      - base
      - extras
      - updates
  when: local_repo|bool

# Local EPEL Repo
- block:
  - name: Remove Regular epel-release rpm
    yum:
      name: epel-release
      state: absent
  - name: Local EPEL Repo
    yum_repository:
      name: "epel"
      description: "Locally built RPMS"
      baseurl: "{{repo_base_url}}/epel/$releasever/$basearch"
      gpgcheck: no
      proxy: "_none_"
      enabled: no
      file: local-epel
      cost: "10"
  when: local_repo|bool
- block:
    - name: Install epel rpm
      yum:
        name: epel-release
        state: present
  when: not local_repo|bool

# Local RPM repo
- block:
  - name: Locally built RPMS
    yum_repository:
      name: "local-rpms"
      description: "Locally built RPMS"
      baseurl: "{{repo_base_url}}/local-rpms"
      gpgcheck: no
      proxy: "_none_"
      enabled: yes
      file: local
      cost: "10"
  when: local_repo|bool

# Local GPFS RPMS
- block:
  - name: Local GPFS RPMS
    yum_repository:
      name: "local-gpfs-{{item}}"
      description: "Local centos repo {{item}}"
      baseurl: "{{repo_base_url}}/gpfs/{{item}}"
      gpgcheck: no
      proxy: "_none_"
      enabled: no
      file: local-rpms
      cost: "10"
    loop: "{{gpfs_repos}}"
  when: local_repo|bool
