---
- name: install apache httpd
  yum:
    name:
      - httpd
    state: present
  notify: restart web
- name: allow apache to make connections
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes
