---
- name: install ipaserver
  include_tasks: "rhel{{ansible_distribution_major_version}}.yml"
- name: build server configuration script
  template:
    src: ipaserver_config.sh.j2
    dest: /root/ipaserver_config.sh
    mode: "0755"
# - name: configure server
#   command: /root/ipaserver_config.sh
#   args:
#     creates: /etc/ipa/default.conf
#     chdir: /root
