---
- name: install nifi
  unarchive:
    remote_src: yes
    src: "{{nifi_url}}"
    dest: "/opt"
    owner: nifi
    group: nifi
    creates: "/opt/nifi-{{nifi_version}}"

- name: nifi directory permission
  file:
    path: "/opt/nifi-{{nifi_version}}"
    owner: nifi
    group: nifi
    recurse: yes

- name: nifi dir link
  file:
    src: "/opt/nifi-{{nifi_version}}"
    dest: /opt/nifi
    owner: nifi
    group: nifi
    state: link

- name: install nifi service
  template:
    src: nifi.service.j2
    dest: /etc/systemd/system/nifi.service
    mode: "0644"
    owner: root
    group: root
  notify: restart nifi

- name: install nifi properties
  template:
    src: nifi.properties.j2
    dest: /opt/nifi/conf/nifi.properties
    mode: "0644"
    owner: nifi
    group: nifi
  notify: restart nifi

- name: install nifi state management
  template:
    src: state-management.xml.j2
    dest: /opt/nifi/conf/state-management.xml
    mode: "0644"
    owner: nifi
    group: nifi
  notify: restart nifi
