---
- name: Create facts.d directory
  file:
    path: "/etc/ansible/facts.d"
    state: "directory"

- name: Install nsd server disk device task
  template:
    src: extra_disks.fact.j2
    dest: "/etc/ansible/facts.d/extra_disks.fact"
    mode: "0755"
  register: result

- name: Reload facts
  setup: ~
  when: result is changed
