---
- name: Create facts.d directory
  file:
    path: "/etc/ansible/facts.d"
    state: "directory"

- name: Install nsd server disk device task
  copy:
    src: extra_disks.fact
    dest: "/etc/ansible/facts.d/extra_disks.fact"
    mode: "0755"
