---
- block:
    - yum_repository:
        name: local-influx-rhel
        description: Local InfluxDB Repository
        baseurl: "{{repo_base_url}}/influxdb/"
        file: local-influx
        cost: "10"
        gpgcheck: no
      name: Local Influx yum repo
  when: local_repo|bool

- block:
    - yum_repository:
        name: influx-rhel
        description: InfluxDB Repository
        baseurl: https://repos.influxdata.com/rhel/$releasever/$basearch/stable
        file: influx
        gpgcheck: no
      name: setup Influx yum repo
  when: not local_repo|bool
