---
- name: reboot
  shell: sleep 5 && reboot
  async: 1
  poll: 0
  ignore_errors: yes
  notify: wait for boot

- name: wait for boot
  wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 5
    timeout: 300
