---
- name: Stop NetworkManager
  service:
    name: NetworkManager
    state: stopped
- name: configure Network Manager
  ini_file:
    path: /etc/NetworkManager/NetworkManager.conf
    section: main
    option: dns
    value: none
  notify: restart nm
- name: update resolv.conf
  template:
    dest: /etc/resolv.conf
    src: resolv.conf.j2
    owner: root
    group: root
    mode: '0644'
  notify: restart nm
