---
# Network manager saves it's configuration on shutdown,
# so it must be shutdown before the config file is edited
- debug:
    var: nameservers
- name: Override DHCP nameservers
  command: >
    nmcli device modify {{item}} ipv4.ignore-auto-dns 1
  when: item != "lo"
  loop: "{{ansible_facts.interfaces}}"
- name: Set new DNS Servers
  command: >
    nmcli device modify {{item}} ipv4.dns {{nameservers|join(",")}}
  when: item != "lo"
  loop: "{{ansible_facts.interfaces}}"
- name: Ensure NetworkManager is still running
  service:
    name: NetworkManager
    state: restarted
