---
# Network manager saves it's configuration on shutdown,
# so it must be shutdown before the config file is edited
- debug:
    var: nameservers
- name: get nm connection names
  command: >
    nmcli -t -f NAME connection show
  register: results
- set_fact:
    nm_connections: "{{results.stdout_lines}}"
- name: Override DHCP nameservers
  command: >
    nmcli connection modify "{{item}}" ipv4.ignore-auto-dns yes
  loop: "{{nm_connections}}"
- name: Set new DNS Servers
  command: >
    nmcli connection modify "{{item}}" ipv4.dns {{nameservers|join(",")}}
  loop: "{{nm_connections}}"
- name: Ensure NetworkManager is still running
  service:
    name: NetworkManager
    state: restarted
