---
- name: Install pbs.conf file
  template:
    src: pbs.conf.j2
    dest: /etc/pbs.conf
  vars:
    pbs_server: "{{ groups['frontend'] }}"
  notify: restart pbs
- name: Install PBSPro server
  yum:
    name: pbspro-server
    state: present
  notify: restart pbs
- name: PBS initial node registration
  template:
    src: pbs_nodes.txt.j2
    dest: /root/pbs_nodes
