---
- block:
    - yum_repository:
        name: local-grafana
        description: local Grafana repo
        baseurl: "{{repo_base_url}}/grafana/"
        cost: "10"
        file: local-grafana
        gpgcheck: no
      name: local Grafana Repository
  when: local_repo|bool

- block:
    - yum_repository:
        name: grafana
        description: Grafana Yum Repository
        baseurl: "{{grafana_repo_url}}"
        gpgkey: "{{grafana_rpm_key_url}}"
        file: grafana
      name: grafana repository
  when: not local_repo|bool
