---
- yum_repository:
    name: grafana
    description: Grafana Yum Repository
    baseurl: https://packages.grafana.com/oss/rpm
    gpgkey: https://packages.grafana.com/gpg.key
  name: grafana repository
