---
- name: python semanage bindings
  yum:
    name: libsemanage-python
    state: present
- name: config selinux for nfs home dirs
  seboolean:
    name: use_nfs_home_dirs
    state: yes
    persistent: yes
