---
- name: python semanage bindings
  yum:
    name: "{{ 'libsemanage-python' if ansible_distribution_major_version == '7' else 'libsemanage-python3' }}"
    state: present
- name: config selinux for nfs home dirs
  seboolean:
    name: use_nfs_home_dirs
    state: yes
    persistent: yes
