---
- name: Install CherryPy
  yum:
    name: python-cherrypy
    state: installed
- name: Unpack grafana bridge
  unarchive:
    src: zimonGrafanaIntf_v3.1.tar
    dest: /opt/
    creates: /opt/zimonGrafanaIntf_v3.1
- name: Symlink zimonGrafanaIntf
  file:
    state: link
    src: /opt/zimonGrafanaIntf_v3.1
    dest: /opt/zimon-grafana
- name: install bridge unit file
  copy:
    dest: /etc/systemd/system/zimon-bridge.service
    content: |
        [Unit]
        Description=ZIMON-Grafana bridge service
        After=pmcollector.service

        [Service]
        Type=simple
        ExecStart=/usr/bin/python /opt/zimon-grafana/zimonGrafanaIntf.py
        KillMode=process

        [Install]
        WantedBy=multi-user.target
- name: enable and activate bridge serivce
  service:
    name: zimon-bridge
    enabled: yes
